management:
  security:
    enabled: false
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${env.git.uri}
          username: ${env.git.username}
          password: ${env.git.password}
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
server:
  port: 8888
org:
  revo:
    env:
      users:
      -  email: revo
         enable: true
         locked: true
         password: $2a$10$nMXQGWFcd01aMI67ubPVrO5oq5rByWzlp.ZKj8mT/S7upiiyrmkhC
         type: 111