server:
  port: ${env.port:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  security:
    enabled: false
org:
  revo:
    env:
      users:
      -  email: revo
         enable: true
         locked: true
         password: $2a$10$nMXQGWFcd01aMI67ubPVrO5oq5rByWzlp.ZKj8mT/S7upiiyrmkhC
         type: 111
