env:
  eureka:
    host: https://revo:revo@revotubeeureka.cfapps.io/eureka/
  auth:
    host: https://revotubeauth.cfapps.io/auth/
  schema: https
  port: 8080

spring:
  rabbitmq:
    virtual-host: rlgahcfz
    username: rlgahcfz
    host: rhino.rmq.cloudamqp.com
    password: M_Bbzo_sQtkKofEHrW_KcTA5h2U43-bq
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost:8080}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${random.value}}
    nonSecurePort: 80
    statusPageUrl: ${env.schema}://${eureka.instance.hostname}${server.context-path}/info
    healthCheckUrl: ${env.schema}://${eureka.instance.hostname}${server.context-path}/health
  client:
    serviceUrl:
        defaultZone: ${env.eureka.host}      
management:
  security:
    enabled: false      
security:
  oauth2:
    client:
      client-id: revo
      client-secret: revo
      access-token-uri: ${env.auth.host}oauth/token
      user-authorization-uri: ${env.auth.host}oauth/authorize
      scope: read
    resource:
      user-info-uri: ${env.auth.host}user
cloud:
  aws:
   credentials:
     accessKey: AKIAJ65XDQDV52UWVL2A
     secretKey: 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
   region:
     auto: false
     static: eu-west-1
