server:
  port: ${env.port:9999}
  context-path: /auth
  use-forward-headers: true
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost:${server.port}}
    statusPageUrl: ${env.schema}://${eureka.instance.hostname}${server.context-path}/info
    healthCheckUrl: ${env.schema}://${eureka.instance.hostname}${server.context-path}/health
spring:
  data:
    mongodb:
      database: CloudFoundry_7njjtl29_n4b5s4hv
      port: 35065
      password: cMgki4oO0NJ4K1Dx22U7SWJsUWpHJG9z
      username: CloudFoundry_7njjtl29_n4b5s4hv_2ev76rnj
      host: ds235065.mlab.com
  redis:
    host: redis-16411.c15.us-east-1-4.ec2.cloud.redislabs.com
    password: rkorp6odDMPssu8w
    port: 16411
  session:
    store-type: redis
org:
  revo:
    env:
      users:
      -  email: ashraf1abdelrasool@gmail.com
         enable: true
         id: 1
         imageUrl: https://s3-eu-west-1.amazonaws.com/static-revo/static/assets/images/a5.jpg
         info: this is sample info about me you are welcome
         locked: true
         name: ashraf
         password: $2a$10$nMXQGWFcd01aMI67ubPVrO5oq5rByWzlp.ZKj8mT/S7upiiyrmkhC
         phone: 1120266849
         type: 111
