server:
  port: ${env.port:8083}
  context-path: /feedback
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost:${server.port}}
    statusPageUrl: ${env.schema}://${eureka.instance.hostname}${server.context-path}/info
    healthCheckUrl: ${env.schema}://${eureka.instance.hostname}${server.context-path}/health
spring:
  data:
    mongodb:
      database: CloudFoundry_7njjtl29_v8vn3s1p
      port: 35775
      password: sz-F-m3_76Mzd5C61s6lbEnW3JlKmm0W
      username: CloudFoundry_7njjtl29_v8vn3s1p_nj5qf53f
      host: ds235775.mlab.com
