env:
  eureka:
    host: http://revo:revo@localhost:8761/eureka/
  auth:
    host: http://localhost:9999
  schema: http




env:
  eureka:
    host: https://revo:revo@revotubeeureka.cfapps.io/eureka/
  auth:
    host: https://revotubeauth.cfapps.io
  schema: https
  port: 8080
